Data quality
LEAD-Machine-Learning/kreuzberg-ml pull request #3
Opened 2022-05-17 12:15 UTC by tahleen-rahman

2022-05-19 08:59 UTC, iyalchyk requested changes

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +    IMAGE = 'image'
If these types are not supported, you should not add this code. The developer who is going to extend the toolbox for these types can add these enum object by themselves (or maybe this developer will decide to add some different types, e.g. MONOCOLOR_IMAGE).

Please remove unsupported types. Instead, you can either create a ticket on GitHub issues to implement tools for images, videos, audios.

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/test_data_quality.py
> +import sys
tests should go to the "tests" folder and follow the same package hierarchy. In this case: `tests/data_quality/test_data_quality.py`

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/test_data_quality.py
> +test_duplicates()
tests will be executed by pytest, which provides much more flexible way to run the tests. Here, you force the tests to be executed under all circumstances, although I might want to run just one test.

Please remove these two statements with explicit tests execution.

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/test_data_quality.py
> +    df = pd.read_csv('../../../src/tests/sample_data/melb_1000.csv')
Such hard-coded pathes are hard to maintain. This is how it should be done (assuming you puth the "sample_data" directory in the same folder with the test script in the tests folder:
```
from pathlib import Path

THIS_DIR = Path(__file__).parent
melb_1000_file_path = THIS_DIR / 'sample_data/melb_1000.csv'
```

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +class DataQuality(ABC):
Why do you inherit from ABC? If it is going to be an abstract class, then you should not create and test DataQuality instances in the tests script. In this case, I don't see any abstract methods, so I would keep this class non-abstract. If it is needed, we can extract some methods to a new abstract class like "AbstractDataQuality".

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._logger = getLogger(__name__)
logger does not have to be associated with a class, and we do not want to create new loggers references for every object. Thus, it's better to put the logger in the module scope (above the class).

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +    def report(self):
This method is doing two very different things:
1. Calculating the statistics
2. Printing the statistics

First task is very important and must be tested extensively with unit-tests. Second task is not important - if users have statistics, they can easily print it on their own, or decide to print it in a different manner.

Thus, there must be a method like `def calc_stats` which would return, let's say, a dictionary. We can test it in our unit-tests.
Then the method `print_stats` would run the method `calc_stats` inside the body and would print it like you are doing here. Theoretically, this method could be tested too, but it's not that important.

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        if self.check_time_index(df.index):
What if it's a multi-index? What if we use this tool for a dataframe with no index (i.e. indexed by row number), where timeseries data is in a plain column? Especially the latter case could be quite common, because I may forget to apply indexing to a dataframe when using this tool. I think, the logic here should be more detailed.

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        # TODO other types
See my other comment regarding TODOs. Please delete this TODO comment.

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        """Simple inference method to dataset type."""
See my other comment regarding the docstrings. This docstring is useless, could you delete it?

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +    def check_time_index(index: Index) -> bool:
Does it work? I don't see a "self" reference in the method signature.

This method can be static. Alternatively, you can convert these static methods to plain functions in the module level (not in a class).

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        if not perc:
multi-variate conditional output is evil. One way to improve it would be to return two variables - "count, perc" - all the time. In case perc is 0, we return it as 0.

Another solution is to calculate the count only, and calcualte the percentage in the calling method (e.g. calc_statistics"), since its' a very simple operation just to divide all counts on the same values len(df).

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        perc_ = count / len(self.df)
letters are free, you can use them all :)
Could you rename it to something like "percentage" or even "null_values_percentage"?

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        """
the parameter name "perc" is not clear. When I looked into the code, I understood that it defines whether the method should return the percentage. I would just remove this parameter and return the percentage all the time. If needed, you can create a separate method to remove just counts, and extract the counts logic to it, but it is not necessary to do now.

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._warnings = []
this field `_warnings` is not used

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._df_type = None
this field `_df_type` is not used

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +                 severity: Optional[str] = None):
this parameter `severity` is not used

2022-05-19 08:59 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +    def __init__(self,
please remove all parameters and fields, which are not used

2022-05-30 11:20 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    Enum of supported dataset types.
made it supported df types

2022-05-30 11:21 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    # TODO currently only the above 2 are supported
done

2022-05-30 11:21 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    TABULAR = 'tabular'
done

2022-05-30 11:22 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    IMAGE = 'image'
done

2022-05-30 11:22 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/test_data_quality.py
> +import sys
I need your assistance  in this @iyalchyk  I had troubles importing

2022-05-30 11:29 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/test_data_quality.py
> +    df = pd.read_csv('../../../src/tests/sample_data/melb_1000.csv')
done

2022-05-30 11:30 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +class DataQuality(ABC):
done

2022-05-30 11:44 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._logger = getLogger(__name__)
done

2022-05-30 11:45 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        # TODO other types
done

2022-05-30 11:46 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        if self.check_time_index(df.index):
commented this part for now since I dont use it rn

2022-05-30 11:46 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        """Simple inference method to dataset type."""
done

2022-05-30 11:47 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    def check_time_index(index: Index) -> bool:
updated

2022-05-30 11:48 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        perc_ = count / len(self.df)
done

2022-05-30 11:50 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._warnings = []
comented. need later

2022-05-30 11:51 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._df_type = None
commented, need later

2022-05-30 11:51 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +                 severity: Optional[str] = None):
commented, need later

2022-05-30 11:52 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._dtypes = dtypes
commented, need later

2022-05-30 11:52 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._random_state = random_state
removed

2022-05-30 11:52 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    def __init__(self,
done

2022-05-30 11:53 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +class DataQuality(ABC):
updated anyway, but why?

2022-05-30 12:34 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        if not perc:
done

2022-05-30 12:34 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +        """
done

2022-05-30 12:36 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    def report(self):
this report function can be renamed to print_stats. Bcz we already have functions to calc stats

2022-05-30 14:06 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/test_data_quality.py
> +import sys
i solved this

2022-05-30 14:07 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/test_data_quality.py
> +test_duplicates()
also solved this

2022-05-30 14:34 UTC, tahleen-rahman commented
@iyalchyk @yalchik Can you plz re -review the PR

2022-06-03 13:28 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +class DataQuality(ABC):
Let's say, the class name is the only thing you know. What can you conclude from it? Can you imagine a "data quality" object in real life? Can you say if there must be only one data quality object in the world, or many? If many, how many of data qualities we might have if we have one source of data?

On the other hand, "DataFrameStatistics" can be imagined as a table describing some statistical values related to a data frame. We can even draw in on paper, so it's easy to imagine. Then, we can immediately derive that it is built on top of data frames. Moreover, it has one-to-one relation with a given data frame, because we would not expect many statistics tables for one data frame. This is exactly how this class is built. Since we can get all these hints from the name, it's a better name for the class you created.

2022-06-03 13:32 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +    Enum of supported dataset types.
I see the docstring is still duplicating the enum name. The enum has name "DataFrameType", and you describe it as "Supported dataframe types." - there is no new information in this explanation. Please remove it.

2022-06-03 13:40 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        if self.check_time_index(df.index):
Pushing commented code is a bad practice. We should not keep any commented code in the repo. Please delete it.

2022-06-03 13:42 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._df_type = None
Pushing commented code is a bad practice. We should not keep any commented code in the repo. Please delete it. When we need it, we can easily write it. If you still think it's useful, you can create a separate branch and push the unfinished code there.

2022-06-03 13:42 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +                 severity: Optional[str] = None):
Pushing commented code is a bad practice. We should not keep any commented code in the repo. Please delete it. When we need it, we can easily write it. If you still think it's useful, you can create a separate branch and push the unfinished code there.

2022-06-03 13:42 UTC, iyalchyk commented on src/kreuzbergml/data_quality/data_quality.py
> +        self._dtypes = dtypes
Pushing commented code is a bad practice. We should not keep any commented code in the repo. Please delete it. When we need it, we can easily write it. If you still think it's useful, you can create a separate branch and push the unfinished code there.

2022-06-03 15:16 UTC, iyalchyk requested changes

2022-06-03 15:16 UTC, iyalchyk commented on src/kreuzbergml/data_quality/DataFrameStatistics.py
> +    def check_periodtime_index(self, index: Index) -> bool:
Since you are checking only None, you could simplify the method to return True if index is DatetimeIndex or PeriodIndex, otherwise False. Then you would check `if not is_periodindex_df` instead of `if is_periodindex_df != None:`

2022-06-10 09:16 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +    Enum of supported dataset types.
done

2022-06-10 09:27 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +                 severity: Optional[str] = None):
done

2022-06-10 09:27 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/data_quality.py
> +class DataQuality(ABC):
thanks

2022-06-10 09:28 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/test_data_quality.py
> +import sys
i actually for got to push my commits

2022-06-10 09:59 UTC, tahleen-rahman commented on src/tests/test_data_quality.py
> +sys.path.append("../kreuzbergml/data_quality")
done

2022-06-10 10:00 UTC, tahleen-rahman commented on src/tests/test_data_quality.py
> +    melb_1000_file_path = THIS_DIR / 'sample_data/melb_1000.csv'
DONE. What is os-independent operator form?

2022-06-10 10:09 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/DataFrameStatistics.py
> +        return dupes_dict, cols_with_dupes, null_cols
done

2022-06-10 10:16 UTC, tahleen-rahman commented on src/kreuzbergml/data_quality/DataFrameStatistics.py
> +                print(f"Column '{col}' has {count} NaN values which comprise {round(percentage_nulls, 2)}% of all rows")
Thanks

2022-06-17 14:35 UTC, merged