Param factory dev
LEAD-Machine-Learning/kreuzberg-ml pull request #4
Opened 2022-05-20 13:02 UTC by Priapos1004

- added classes for the following models:
--- RandomForestClassifier
--- SVC and LinearSVC
--- MLPClassifier
--- DecisiontreeClassifier
--- KNeighborsClassifier

2022-05-20 13:12 UTC, iyalchyk requested changes

2022-05-20 13:12 UTC, iyalchyk commented on src/kreuzbergml/model/param_factory.py
> +            "gamma": [1, 0.1, 0.01, 0.001],
Such sequences can be replaced with "numpy.logspace" statements
See: https://numpy.org/doc/stable/reference/generated/numpy.logspace.html

2022-05-20 13:12 UTC, iyalchyk commented on src/kreuzbergml/model/param_factory.py
> +            "solver": ["lbfgs", "liblinear"],
It doesn't make sense to test different solvers in the hyperparameters optimization, because they will not affect the model. We need to decide which one we want to use based on the data characteristics. Let's keep just "lbfgs".

2022-05-20 13:12 UTC, iyalchyk commented on src/kreuzbergml/model/param_factory.py
> +            "n_estimator": [8, 16, 32, 64, 100, 200, 500, 1000],
Such sequences can be replaced with "numpy.logspace" statements with base=2.
See: https://numpy.org/doc/stable/reference/generated/numpy.logspace.html

2022-05-20 13:12 UTC, iyalchyk commented on src/kreuzbergml/model/param_factory.py
> +            "solver": ["sgd", "adam"],
Again, let's not continue solver as a hyperparameters. Let's keep it default. So, you can remove this line.

2022-05-20 13:16 UTC, iyalchyk commented
you might also want to use numpy.geomspace for some cases

2022-05-23 08:06 UTC, Priapos1004 commented on src/kreuzbergml/model/param_factory.py
> +            "gamma": [1, 0.1, 0.01, 0.001],
done

2022-05-23 08:07 UTC, Priapos1004 commented on src/kreuzbergml/model/param_factory.py
> +            "solver": ["lbfgs", "liblinear"],
done

2022-05-23 08:07 UTC, Priapos1004 commented on src/kreuzbergml/model/param_factory.py
> +            "n_estimator": [8, 16, 32, 64, 100, 200, 500, 1000],
done

2022-05-23 08:07 UTC, Priapos1004 commented on src/kreuzbergml/model/param_factory.py
> +            "solver": ["sgd", "adam"],
done

2022-06-16 07:14 UTC, merged